CK = ""
CS = ""
AT = ""
ATS = ""


def set(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET):
    global CK, CS, AT, ATS
    CK = CONSUMER_KEY
    CS = CONSUMER_SECRET
    AT = ACCESS_TOKEN
    ATS = ACCESS_TOKEN_SECRET
